### ISSUE TITLE
undefined reference to symbol '_ZN3MPI8Datatype4FreeEv' build error

### ISSUE THREAD

**Issue by sefakurtipek** [salehjg/MeshToPointcloudFPS#1]
I'm taking the following error when I write "make" to command window.
Do you have any suggestion for that?

```
/usr/bin/ld: CMakeFiles/FpsCpu.dir/src/hdf5.cpp.o: undefined reference to symbol '_ZN3MPI8Datatype4FreeEv'
//usr/lib/x86_64-linux-gnu/libmpi_cxx.so.20: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/FpsCpu.dir/build.make:409: recipe for target 'FpsCpu' failed
make[2]: *** [FpsCpu] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/FpsCpu.dir/all' failed
make[1]: *** [CMakeFiles/FpsCpu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by salehjg** [comment]
Hi Sefa,

Could you please include the details of your environment?
(Distro, version numbers of G++, CMake, and HDF5)
Does the CMake script execute without any warnings and issues?

I believe you are using an old version of GCC/G++ (possibly older than v5). For example, if you are on CentOS 7.x, enable `devtoolset-7` or later and then build the project. If you have an ArchLinux, it should work without any issues. For Debian families, look for `update-alternatives`.

**Comment by salehjg** [comment]
I am closing this for now, please feel free to re-open it if your issue still persists.
